<a href="https://colab.research.google.com/github/ViktorDickson/computer_vision/blob/main/animal_identification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import sys
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import torch
import torchvision
from PIL import Image
from torchvision import transforms

In [2]:
print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

Platform: linux
Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
---
matplotlib version: 3.10.0
pandas version: 2.2.2
PIL version: 11.3.0
torch version: 2.10.0+cu128
torchvision version: 0.25.0+cu128


In [4]:
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_tensor = torch.tensor(my_list)
my_tensor

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [5]:
my_tensor.shape

torch.Size([4, 3])

In [6]:
my_tensor.dtype

torch.int64

In [7]:
my_tensor.device

device(type='cpu')

In [8]:
# Check if GPUs available via `cuda`
cuda_gpus_available = torch.cuda.is_available()

# Check if GPUs available via `mps`
mps_gpus_available = torch.backends.mps.is_available()

print("cuda GPUs available:", cuda_gpus_available)
print("mps GPUs available:", mps_gpus_available)

cuda GPUs available: True
mps GPUs available: False


In [10]:
my_tensor = my_tensor.to("cuda")
print("my_tensor device:", my_tensor.device)

my_tensor device: cuda:0


In [14]:
up_tensor = my_tensor[:2,:]
down_tensor = my_tensor[2:,:]

up_tensor


tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [15]:
down_tensor

tensor([[ 7,  8,  9],
        [10, 11, 12]], device='cuda:0')